import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/assets/heroVideo.mp4'

import { Inter } from '@next/font/google'

import styled from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

const HeroContainer = styled.section`
position: relative;
text-align: center;
// padding:0 1em;
max-width:1100px;
margin:0 auto;
video{
height:min(50vh,20em);
width:100%;
object-fit:cover;
  border:.5em solid ${({ theme }) => theme.color.accent};
  border-left:0;
  border-right:0;
  
}
h1 {
  color:${({ theme }) => theme.color.darkFont};
  position:absolute;
  left:50%;
  top:50%;
  transform:translate(-50%, -50%);
  font-weight:bold;
  font-size:3em;
  width:100%;
}
@media screen and (min-width: 1200px){
video{

  border:.25em solid ${({ theme }) => theme.color.accent};;
  border-radius:${({ theme }) => theme.border.outer}


}
}
`
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroContainer>
        <h1>Premier Assisted Living in Northern Virginia</h1>
        <video autoPlay loop muted >
          <source src={Hero} type="video/mp4" />
          {/* <source src="movie.ogg" type="video/ogg" /> */}


        </video>
      </HeroContainer>
    </>
  )
}
